<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<head>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
          integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
          crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
            integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
            crossorigin=""></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style type="text/css">
        #page{
            margin: 0 10%;
        }
        #mapid{ height: 60%; width: 100%%; }
        #img { height: 40%; width: 100%;}
    </style>
    <title>TP4</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>

<div id="page">
    <div id="psuedoConnexion" style="border: solid black 1px">
        <legend>Jouer a city locate</legend>
        <label for="psuedo">Psuedo pour la partie :</label>
        <input id="psuedo" type="text">
        <p id="erreurPsuedo"></p>
        <hr>
        <button id="seConnecterPourJouer" class="btn btn-info">Se connecter</button>
        <button id="play" class="btn btn-success">Jouer</button>
    </div>
    <div id="playGame">
        <h3 id="bienvenuePsuedo"></h3>
        <h4>Choisissez une carte</h4>
        <input  type="radio"  class="btn btn-primary" name="ville"  id="lyon"><label for="lyon">Lyon</label><br>
        <input type="radio" name="ville" id="belfort" checked="checked"> <label for="belfort">Belfort</label><br>
        <h4>Choisissez un niveau</h4>
        <div id="lvl">
            <input type="radio" class="btn btn-primary" name="difficulte" checked="checked"  id="facile"><label for="facile">Facile</label><br>
            <input type="radio" name="difficulte" id="normal"><label for="normal">Normal</label><br>
            <input type="radio" name="difficulte" id="difficile"><label for="difficile">Difficile</label>
        </div>
        <hr>
        <button id="startGame" class="btn btn-success">Jouer !</button>
    </div>
    <div id="game">
        <h3 id="psuedoPartie"></h3>
        <h4 id="score">Score :</h4>
        <h4 id="niveau">Niveau 1/10</h4>
        <h4 id="time">Temps :  </h4>
        <button id="pause">Pause</button>
        <div id="mapid"></div>
        <div id="img"> <img id="image"></div>
    </div>
    <button id="resume">Reprendre</button>

    <div id="fin">
        <h4>Fin de la partie</h4>
        <h5 id="finScore"></h5>
        <p id="meilleurScore"></p>
        <button id="accueil" class="btn btn-info">Accueil</button>
    </div>
</div>

<script type="text/javascript">
    var monToken;
    var psuedo;
    var time=0;
    $(function(){
        monToken = "";
        $.get("http://localhost:8080/getToken",function(data){
            monToken = data;
        });
        $("#playGame").hide();
        $("#mapid").hide();
        $("#game").hide();
        $("#fin").hide();
        $("#resume").hide();
    });

    $("#play").click(function () {
        $("#game").hide();
        psuedo=$("#psuedo").val();
        if (psuedo.length<4){
            $("#erreurPsuedo").addClass("alert alert-danger");
            $("#erreurPsuedo").text("Votre psuedo doit faire au moins 4 caracteres");
            return;
        }
        $("#erreurPsuedo").removeClass("alert alert-danger");
        $("#erreurPsuedo").text("");

        $("#psuedoConnexion").hide();
        $("#bienvenuePsuedo").text("Bienvenue "+psuedo);
        $("#playGame").show();

        
    });

    $("#startGame").click(function (data) {

        var partie=[];
        if (document.getElementById('lyon').checked) partie['ville']="lyon";
        else partie['ville']="belfort";


        if (document.getElementById('facile').checked) partie['difficulte']="facile";
        else if (document.getElementById('normal').checked) partie['difficulte']="normal";
        else  partie['difficulte']="difficile";

        $("#game").show();
        $("#mapid").show();

        var mymap = L.map('mapid').setView([47.6333, 6.8667], 11);
        L.tileLayer('https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {
            maxZoom: 18,
            id: 'mapbox.streets',
        }).addTo(mymap);

        $("#playGame").hide();
        $("#psuedoPartie").text(psuedo+ " vous jouez avec "+partie['ville']+" en difficulté "+partie['difficulte']);
        $.post("http://localhost:8080/play/games",{psuedo:psuedo , ville:partie['ville']},function (data) {

            var interval=setInterval(function () {
                time++;
                document.getElementById("time").innerText="Temps : "+time+" Secondes";
            }, 1000);
            var ville = data['ville'];
            var images = data['images'];
            var indice=0;
            var distance;
            var scoreTotal=0;
            switch (partie['difficulte']) {
                case 'facile':
                    distance=150;
                    break;
                case 'normal':
                    distance=125;
                    break;
                case 'difficile':
                    distance=100;
                    break;
            }
            mymap.panTo(new L.LatLng(ville['latitudeCarte'], ville['longitudeCarte']));
            mymap.setZoom(13);
            document.getElementById("image").src = images[indice]['lienImg'];

            mymap.on('click', function (e) {
                    const sleep = (milliseconds) => {
                        return new Promise(resolve => setTimeout(resolve, milliseconds))
                    };
                    if (indice+1==images.length) {
                        sleep(2000).then(() => {
                            $("#game").hide();
                            $("#fin").show();
                            $("#finScore").text("Felicitation " + psuedo + " vous avez un score de " + scoreTotal);
                            $.post("http://localhost:8080/bestScore", {
                                psuedo: psuedo,
                                ville: partie['ville'],
                                score :scoreTotal
                            }, function (data) {
                                var indice=1;
                                var str="Listes des meilleurs scores : \n";
                                data.forEach(function (d) {
                                    str+=indice+") "+d['nomJoueur']+" score : "+d['score']+"\n";
                                    indice++;
                                });
                                document.getElementById("meilleurScore").innerText=str;
                            });
                        });
                    };

                    var marker = L.marker(e.latlng).addTo(mymap);
                    var latLongMarker = marker.getLatLng();
                    var latLieux =parseFloat(images[indice]['latitude']);
                    var longLieux=parseFloat(images[indice]['longitude']);
                    var latLongLieux = L.latLng(latLieux,longLieux);


                    var distanceTo = latLongLieux.distanceTo(latLongMarker);
                    var score=0;

                    if (distanceTo<distance) score=5;
                    else if (distanceTo<2*distance) score=3;
                    else if (distanceTo<3*distance) score=1;
                    
                    
                    if (time<2) score=4*score;
                    else if(time<5) score=2*score;
                    else if(time>10) score=0;


                    var marker1=L.marker(latLongLieux).addTo(mymap);
                    var firstpolyline = new L.Polyline([latLongMarker,latLongLieux], {
                        color: 'red',
                        weight: 3,
                        opacity: 0.5,
                        smoothFactor: 1
                    });
                    firstpolyline.addTo(mymap);


                    sleep(2000).then(() => {
                        mymap.removeLayer(marker);
                        mymap.removeLayer(marker1);
                        mymap.removeLayer(firstpolyline);
                        time=0;
                    });
                scoreTotal+=score;
                indice++;
                document.getElementById("score").innerText="Score "+scoreTotal;
                document.getElementById("image").src = images[indice]['lienImg'];
                document.getElementById("niveau").innerText="Niveau "+(indice+1)+"/10";


            });
        });
   });
    $("#accueil").click(function () {
        window.location.reload(true);
    });

    $("#pause").click(function () {
        $("#resume").show();
        $("#game").hide();
        clearInterval(interval);
    });

    $("#resume").click(function () {
        $("#game").show();
        $("#resume").hide();
    });




</script>
</body>
</html>
